### ISSUE TITLE
Missing module Sharp?

### ISSUE THREAD

**Issue by fearghalmurphy** [sagidM/s3-resizer#14]
Forgive my lack of knowledge on AWS - i'm kind of a newbie but when i try to test the lambda the following gets returned - is there a missing module or do i need to do anything additional to your tutorial? Thank you! Any help is appreciated.

Response:
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'sharp'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}

Request ID:
"a9d515ef-c4a3-4b8b-ba30-f8d2c643bc0b"

Function Logs:
START RequestId: a9d515ef-c4a3-4b8b-ba30-f8d2c643bc0b Version: $LATEST
2020-03-31T13:40:02.304Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'sharp'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'sharp'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
END RequestId: a9d515ef-c4a3-4b8b-ba30-f8d2c643bc0b
REPORT RequestId: a9d515ef-c4a3-4b8b-ba30-f8d2c643bc0b	Duration: 763.36 ms	Billed Duration: 800 ms	Memory Size: 768 MB	Max Memory Used: 30 MB	
Unknown application error occurred
Runtime.ImportModuleError

**Comment by sagidM** [comment]
@fearghalmurphy thank you for the issue.
How exactly have you set up the lambda?
Notice that you should upload a zip file from https://github.com/sagidM/s3-resizer/releasess, not just `index.js`

**Comment by sagidM** [comment]
Closing this issue. You've probably uploaded a single `index.js` whereas should have a zip file from [the releases](https://github.com/sagidM/s3-resizer/releases).
